spring.application.name=groovelink-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/groovelink
spring.datasource.username=groovelink
spring.datasource.password=groovelink

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true 
spring.jpa.open-in-view=false

app.seed.default-admin.enabled=false
app.seed.default-admin.username=${APP_DEFAULT_ADMIN_USERNAME:admin}
app.seed.default-admin.email=${APP_DEFAULT_ADMIN_EMAIL:admin@example.com}
app.seed.default-admin.password=${APP_DEFAULT_ADMIN_PASSWORD:change-me}
app.seed.default-admin.cargo=${APP_DEFAULT_ADMIN_CARGO:SUPERADMIN}

# JWT Configuration
app.jwt.secret=${APP_JWT_SECRET:GrooveLink_SuperSecureKeyForHS512Algorithm_2026_RequiresMinimumOfSixtyFourBytesForSecurityCompliance_AddingMoreCharacters}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

