-- =========================================
-- TABLA BASE DE USUARIO (JOINED Inheritance)
-- =========================================
CREATE TABLE usuario (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rol VARCHAR(20) NOT NULL
);

-- =========================================
-- PERSONA (inherits from usuario via JOINED)
-- =========================================
CREATE TABLE persona (
    id BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    premium BOOLEAN DEFAULT FALSE NOT NULL
);

-- =========================================
-- EMPRESA (inherits from usuario via JOINED)
-- =========================================
CREATE TABLE empresa (
    id BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    direccion VARCHAR(255) NOT NULL
);

-- =========================================
-- ADMINISTRADOR (inherits from usuario via JOINED)
-- =========================================
CREATE TABLE administrador (
    id BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    cargo VARCHAR(40)
);

-- =========================================
-- PERFIL (1:1 con usuario, via @MapsId)
-- =========================================
CREATE TABLE perfil (
    id BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    descripcion VARCHAR(500),
    foto_perfil BYTEA,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================
-- VALORES MAESTROS
-- =========================================
CREATE TABLE genero (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE aptitud (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) UNIQUE NOT NULL
);

-- =========================================
-- CHATS Y MENSAJES
-- =========================================
CREATE TABLE chat (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    es_grupal BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultimo_mensaje TIMESTAMP
);

CREATE TABLE usuario_participa_chat (
    id_usuario BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    id_chat BIGINT NOT NULL REFERENCES chat(id) ON DELETE CASCADE,
    fecha_union TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_usuario, id_chat)
);

CREATE TABLE mensaje (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    id_chat BIGINT NOT NULL REFERENCES chat(id) ON DELETE CASCADE,
    contenido VARCHAR(2000) NOT NULL,
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================================
-- EVENTOS Y FOTOS
-- =========================================
CREATE TABLE evento (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    ubicacion VARCHAR(255) NOT NULL,
    descripcion VARCHAR(2000) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_final DATE NOT NULL,
    publicado BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE fotoevento (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    codigo_evento BIGINT NOT NULL REFERENCES evento(id) ON DELETE CASCADE,
    es_portada BOOLEAN DEFAULT FALSE,
    nombre_foto VARCHAR(255),
    ruta_archivo VARCHAR(500)
);

CREATE TABLE evento_aptitudes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_evento BIGINT NOT NULL REFERENCES evento(id) ON DELETE CASCADE,
    id_aptitud BIGINT NOT NULL REFERENCES aptitud(id) ON DELETE CASCADE
);

CREATE TABLE evento_generos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_evento BIGINT NOT NULL REFERENCES evento(id) ON DELETE CASCADE,
    id_genero BIGINT NOT NULL REFERENCES genero(id) ON DELETE CASCADE
);

-- =========================================
-- RELACIONES DE PERSONA CON VALORES
-- =========================================
CREATE TABLE persona_aptitudes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL REFERENCES persona(id) ON DELETE CASCADE,
    id_aptitud BIGINT NOT NULL REFERENCES aptitud(id) ON DELETE CASCADE
);

CREATE TABLE persona_generos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL REFERENCES persona(id) ON DELETE CASCADE,
    id_genero BIGINT NOT NULL REFERENCES genero(id) ON DELETE CASCADE
);

-- =========================================
-- INTERACCIONES DE PERSONA CON EVENTOS
-- =========================================
CREATE TABLE persona_comentario_evento (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL REFERENCES persona(id) ON DELETE CASCADE,
    codigo_evento BIGINT NOT NULL REFERENCES evento(id) ON DELETE CASCADE,
    texto VARCHAR(1000) NOT NULL,
    megustas INTEGER DEFAULT 0,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE persona_une_evento (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL REFERENCES persona(id) ON DELETE CASCADE,
    codigo_evento BIGINT NOT NULL REFERENCES evento(id) ON DELETE CASCADE,
    fecha_inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE persona_megusta_evento (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL REFERENCES persona(id) ON DELETE CASCADE,
    codigo_evento BIGINT NOT NULL REFERENCES evento(id) ON DELETE CASCADE,
    fecha_megusta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_usuario, codigo_evento)
);

-- =========================================
-- REPORTES
-- =========================================
CREATE TABLE reporte (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_reportero BIGINT REFERENCES usuario(id) ON DELETE SET NULL,
    tipo_contenido VARCHAR(50) NOT NULL,
    id_contenido BIGINT NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    detalle_adicional VARCHAR(1000),
    fecha_reporte TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revisado_por BIGINT REFERENCES administrador(id) ON DELETE SET NULL,
    estado VARCHAR(20) DEFAULT 'pendiente',
    fecha_revision TIMESTAMP
);

-- =========================================
-- INDICES
-- =========================================
CREATE INDEX idx_evento_nombre ON evento(nombre);
CREATE INDEX idx_evento_ubicacion ON evento(ubicacion);
CREATE INDEX idx_evento_fecha_inicio ON evento(fecha_inicio);
CREATE INDEX idx_evento_publicado ON evento(publicado);
CREATE INDEX idx_chat_ultimo_mensaje ON chat(ultimo_mensaje DESC);
CREATE INDEX idx_reporte_estado ON reporte(estado);
CREATE INDEX idx_reporte_tipo ON reporte(tipo_contenido);
CREATE INDEX idx_persona_comentario_evento ON persona_comentario_evento(codigo_evento);
CREATE INDEX idx_persona_une_evento ON persona_une_evento(codigo_evento);
CREATE INDEX idx_persona_megusta_evento ON persona_megusta_evento(codigo_evento);